# Generated by Django 4.2.2 on 2023-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenew',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
    ]
