# Generated by Django 4.2.2 on 2023-07-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='candidate',
            new_name='candidates',
        ),
    ]
