# Generated by Django 4.2.2 on 2023-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comapany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_employees', models.IntegerField(blank=True, null=True)),
                ('search_employees', models.BooleanField(default=True)),
            ],
        ),
    ]
