# Generated by Django 4.2.2 on 2023-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_candidate_vacancy_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapany',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
    ]
