# Generated by Django 4.2.2 on 2023-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_workers_user_coment'),
        ('core', '0002_comapany'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidate',
            field=models.ManyToManyField(blank=True, to='worker.workers'),
        ),
    ]
