# Generated by Django 4.2.2 on 2023-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comapany_created_at_alter_vacancy_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назавание навыка')),
                ('skill_description', models.TextField(verbose_name='Описание')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы')),
                ('employment', models.CharField(choices=[('full time', 'полный рабочий день'), ('part time', 'частичная занятость'), ('piece work', 'сделаная работа')], default='full time', max_length=10)),
            ],
        ),
    ]
