# Generated by Django 4.2.2 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='employment',
            field=models.CharField(choices=[('full time', 'Полный рабочий день'), ('part time', 'Частичная занятость'), ('piece work', 'Сделаная работа')], default='full time', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, verbose_name='Назавание навыка'),
        ),
    ]
