# Generated by Django 4.2.2 on 2023-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_skill_employment_alter_skill_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='work_experience',
        ),
    ]
