# Generated by Django 4.2.2 on 2023-07-25 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_resume_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_skill_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(choices=[('full time', 'Полный рабочий день'), ('part time', 'Частичная занятость'), ('piece work', 'Сделаная работа')], default='full time', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(default=0, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='worker.workers', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacancy_category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Нет описнания', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Потверждение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='review',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Просметрено'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вазвание вакансии'),
        ),
    ]
