# Generated by Django 4.2.2 on 2023-07-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0007_resume_profile_photo'),
        ('core', '0007_vacancy_employment_vacancy_work_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(to='worker.workers', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacancy_category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='review',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Просметрено'),
        ),
    ]
