# Generated by Django 4.2.2 on 2023-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vacancy_candidates_alter_vacancy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Зарплата'),
        ),
    ]
