# Generated by Django 4.2.2 on 2023-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_vacancy_candidates_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название вакансии:'),
        ),
    ]
