# Generated by Django 4.2.2 on 2023-07-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('expected_salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('job_search', models.BooleanField(default=True, verbose_name='Ищет работу')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField(verbose_name='О себе')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт работы')),
                ('education', models.CharField(max_length=255, null=True, verbose_name='Образование')),
                ('skills', models.CharField(default='SEO', max_length=255, verbose_name='Наваки')),
                ('contacts', models.IntegerField(null=True, verbose_name='контакты')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workers')),
            ],
        ),
    ]
