# Generated by Django 4.2.2 on 2023-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('expected_salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('job_search', models.BooleanField(default=True, verbose_name='Ищет работу')),
            ],
        ),
    ]
