# Generated by Django 4.2.2 on 2023-07-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_resume_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='author',
        ),
    ]
