# Generated by Django 4.2.2 on 2023-07-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_remove_resume_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='author',
        ),
    ]
