# Generated by Django 4.2.2 on 2023-07-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_rename_name_resume_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='user',
            new_name='username',
        ),
    ]
