# Generated by Django 4.2.2 on 2023-06-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workers'),
        ),
    ]
