# Generated by Django 4.2.2 on 2023-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(verbose_name='О себе'),
        ),
    ]
