# Generated by Django 4.2.2 on 2023-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_rename_user_workers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
