# Generated by Django 4.2.2 on 2023-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_resume_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт работы'),
        ),
    ]
