# Generated by Django 4.2.2 on 2023-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contacts',
            field=models.IntegerField(null=True, verbose_name='контакты'),
        ),
    ]
