# Generated by Django 4.2.2 on 2023-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_resume_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Фото сoтрудника'),
        ),
    ]
