# Generated by Django 4.2.2 on 2023-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_resume_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=255, null=True, verbose_name='Образование'),
        ),
    ]
