# Generated by Django 4.2.2 on 2023-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(default=True, max_length=255, verbose_name='Наваки'),
        ),
    ]
