# Generated by Django 4.2.2 on 2023-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.CharField(default='SEO', max_length=255, verbose_name='Наваки'),
        ),
    ]
