# Generated by Django 4.2.2 on 2023-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Пользеватель')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('payment_for_found', models.IntegerField(blank=True, null=True, verbose_name='Денежное поступление')),
                ('bonus_percent', models.IntegerField(blank=True, null=True, verbose_name='Проценты')),
            ],
        ),
    ]
