# Generated by Django 4.2.2 on 2023-07-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_alter_recruit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5),
        ),
    ]
