# Generated by Django 4.2.2 on 2023-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_alter_recruit_bonus_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, max_digits=3, max_length=5, verbose_name='Бонусы платежа'),
        ),
    ]
